Add files via upload

diff --git a/usr/local/recentchanges/scripts/rntchangesfunctions b/usr/local/recentchanges/scripts/rntchangesfunctions
--- a/usr/local/recentchanges/scripts/rntchangesfunctions
+++ b/usr/local/recentchanges/scripts/rntchangesfunctions
@@ -60,12 +60,12 @@ rm -f "${files[@]}" 2> /dev/null
 # test -d "$home_dir" && find "$home_dir" -maxdepth 1 -type f -name '*.gpg' -exec sudo rm -f -- {} +
 }
 generatekey() {
-	# 5.1 porteus   GPG 2.x+ generate key but if 5.01 has GPG2 do it too
+    # 5.1 porteus   GPG 2.x+ generate key but if 5.01 has GPG2 do it too
 
-	xopt=$(mktemp -d /tmp/tmpda.XXXXXX)
-	# if command -v gpg2 >/dev/null 2>&1 || gpg --version | grep -qiE "gnupg.*2|\(GnuPG\) 2"; then
-	if which gpg2 > /dev/null 2>&1 || gpg --version | grep -qiE "gnupg.*2|\(GnuPG\) 2" ; then
-		read -sp "Enter passphrase for new GPG key: " p
+    xopt=$(mktemp -d /tmp/tmpda.XXXXXX)
+    # if command -v gpg2 >/dev/null 2>&1 || gpg --version | grep -qiE "gnupg.*2|\(GnuPG\) 2"; then
+    if which gpg2 > /dev/null 2>&1 || gpg --version | grep -qiE "gnupg.*2|\(GnuPG\) 2" ; then
+        read -sp "Enter passphrase for new GPG key: " p
 cat > $xopt/keyparams.conf <<EOF
 %echo Generating a GPG key
 Key-Type: RSA
@@ -93,69 +93,75 @@ EOF
             remove_gpg
         fi
         echo "GPG key generated for ${email}."
-	else
-		if ! gpg --with-keygrip --list-secret-keys >/dev/null 2>&1; then
-			echo "Gpg 1.4 or outdated version installed please install gpg2. recommended."
-			if which expect > /dev/null 2>&1; then # is expect installed?
-				echo "Use expect. And run the keygen file for 5.01. Remember to remove passphrase after from file."
-			else
-				echo "Expect not installed."
-			fi
-			echo
-			echo "If using gpg 1.4 a key can be made by installing expect and running the keygen file. Then erase the passphrase you entered in the file from the file."
-			echo "In order for it to work with this script the keypair then has to be exported to root with:"
-			echo "gpg --export-secret-keys --armor email > key.asc"
-			echo "then sudo su and  as root"
-			echo  "gpg --import key.asc"
-			echo " gpg --edit-key email  . then set  True, 5, y, quit to trust the key"
-		fi
-		exit 1
-	fi
+    else
+        if ! gpg --with-keygrip --list-secret-keys >/dev/null 2>&1; then
+            echo "Gpg 1.4 or outdated version installed please install gpg2. recommended."
+            if which expect > /dev/null 2>&1; then # is expect installed?
+                echo "Use expect. And run the keygen file for 5.01. Remember to remove passphrase after from file."
+            else
+                echo "Expect not installed."
+            fi
+            echo
+            echo "If using gpg 1.4 a key can be made by installing expect and running the keygen file. Then erase the passphrase you entered in the file from the file."
+            echo "In order for it to work with this script the keypair then has to be exported to root with:"
+            echo "gpg --export-secret-keys --armor email > key.asc"
+            echo "then sudo su and  as root"
+            echo  "gpg --import key.asc"
+            echo " gpg --edit-key email  . then set  True, 5, y, quit to trust the key"
+        fi
+        exit 1
+    fi
 }
 
 setup_exports() {
+
     [[ "$1" = "gui" ]] && { "$app_install"/main ; exit ; }
-	export CMD_LINE="1"
-	[[ "$1" = "query" ]] && { "$app_install"/main "$USR" "$PWD" query ; exit ; }
-	[[ "$1" = "reset" ]] && { "$app_install"/main "$USR" "$PWD" reset ; exit ; }
-	output=$( python3 "$app_install"/src/get_exports.py $USR) ; res=$?
+    export CMD_LINE="1"
+    [[ "$1" = "query" ]] && { "$app_install"/main "$USR" "$PWD" query ; exit ; }
+    [[ "$1" = "reset" ]] && { "$app_install"/main "$USR" "$PWD" reset ; exit ; }
+
+    output=$( python3 "$app_install"/src/get_exports.py $USR) ; res=$?
 
     if [[ $res -ne 0 ]]; then
+        
         if [[ $res -eq 3 ]]; then
             echo "no key found"  # if there is a .gpg in /home/guest/.local/share/recentchanges but now there isnt a gpg key generatekey will clear it the .gpg
         elif [[ $res -eq 4 ]]; then
             echo "inappropriate ioctl or no pinentry." ; echo "if having problems run recentchanges reset" && exit 4
         elif [[ $res -eq 7 ]]; then 
             echo "bad passphrase" && exit 7
+        elif [[ $res -eq 2 ]]; then
+            echo "failed to start user gpg agent" && exit 2
         else
-            echo "couldnt start user gpg agent before root" && exit $res
+            echo "failed to setup environment from $app_install/src/get_exports.py" && exit $res
         fi
     fi
 
-	eval "$output"  # def main(home_dir, user, email, reset=None, database=None, log_fn=print):
-	if ! gpg --list-keys | grep -q $email; then generatekey ; fi  # setup key pair for both user and root
+    eval "$output"
+    if ! gpg --list-keys | grep -q $email; then generatekey ; fi  # setup key pair for user
 }
 
 display() {
 local locale=$1
 if [[ -n "$locale" && "$dspEDITOR" != "false" ]]; then
     if [[ -n "$dspPATH" ]]; then [[ ! -e "$dspPATH" ]] && { echo "dspPATH setting invalid - ${dspPATH} not found" >&2 ; return 1 ; } ; "$dspPATH" "$locale" && return ; echo "Error: Failed to open ${locale} with ${dspPATH}" >&2 ; return 1 ; fi
-	[[ -n "$dspEDITOR" && "$dspEDITOR" != "xed" && "$dspEDITOR" != "featherpad" ]] && echo "$dspEDITOR chosen if using other editor please specify dspPATH" && return 1 || { [[ -z "$dspEDITOR" ]] && return 1 ; }
-	editor_path=$( which $dspEDITOR 2> /dev/null)
-	if [[ -n "$editor_path" ]]; then
-		test -e $editor_path && "$editor_path" "$locale" && return || { ! test -e "$editor_path" && echo couldnt launch $dspEDITOR at "$editor_path" ; }
-	else
-		test -e /usr/bin/$dspEDITOR && /usr/bin/$dspEDITOR "$locale" && return  || { ! test -e /usr/bin/$dspEDITOR && echo couldnt find $dspEDITOR in path or in default /usr/bin please specify dspPATH: "$tomlf" ; }
-	fi
-	return 1
+    [[ -n "$dspEDITOR" && "$dspEDITOR" != "xed" && "$dspEDITOR" != "featherpad" ]] && echo "$dspEDITOR chosen if using other editor please specify dspPATH" && return 1 || { [[ -z "$dspEDITOR" ]] && return 1 ; }
+    editor_path=$( which $dspEDITOR 2> /dev/null)
+    if [[ -n "$editor_path" ]]; then
+        test -e $editor_path && "$editor_path" "$locale" && return || { ! test -e "$editor_path" && echo couldnt launch $dspEDITOR at "$editor_path" ; }
+    else
+        test -e /usr/bin/$dspEDITOR && /usr/bin/$dspEDITOR "$locale" && return  || { ! test -e /usr/bin/$dspEDITOR && echo couldnt find $dspEDITOR in path or in default /usr/bin please specify dspPATH: "$tomlf" ; }
+    fi
+    return 1
 fi
 }
 
+
 # load text editor if user want to display as non root
 output_results() {
-	local file_out="$XDG_RUNTIME_DIR"/file_output
-	if [[ $res -eq 0 ]]; then test -f $file_out && var=$( cat $file_out) && display "$var" ; fi  # test -f $file_out && rm $file_out
-	exit $res
+    local file_out="$XDG_RUNTIME_DIR"/file_output
+    if [[ $res -eq 0 ]]; then test -f $file_out && var=$( cat $file_out) && display "$var" ; fi  # test -f $file_out && rm $file_out
+    exit $res
 }
 
 upt_cache() {
@@ -186,8 +192,8 @@ normalize_frac() {
 }
 
 calculate_csum() {
-local xmode="$1"				;	local file_path="$2"
-local modified_epoch=$3	;	local ino=$4
+local xmode="$1"              ;    local file_path="$2"
+local modified_epoch=$3    ;    local ino=$4
 local sze=$5
 local x=$6
 local delay=$7
@@ -204,79 +210,79 @@ local prev_hash=""
 local max_retries=$x
 
 if [ "$ino" -ge 0 ] 2>/dev/null && [ "$sze" -ge 0 ] 2>/dev/null; then
-	while (( x >= 0 )); do
-		r=""
-	    checks=$( md5sum "$file_path" 2>/dev/null)
-		if [[ -n "$checks" ]]; then
-			checks=${checks%% *}
-			# on second or later iteration and not ctime as ctime could no longer be > mtime now
-			if [[ -n "$prev_hash" &&"$checks" = "$prev_hash" ]]; then
+    while (( x >= 0 )); do
+        r=""
+        checks=$( md5sum "$file_path" 2>/dev/null)
+        if [[ -n "$checks" ]]; then
+            checks=${checks%% *}
+            # on second or later iteration and not ctime as ctime could no longer be > mtime now
+            if [[ -n "$prev_hash" &&"$checks" = "$prev_hash" ]]; then
 
-				if [ "$a_ino" -ge 0 ] 2>/dev/null; then
-					# update only needed stats
-					check_sum=$checks
-					mtime=$modified_epoch
+                if [ "$a_ino" -ge 0 ] 2>/dev/null; then
+                    # update only needed stats
+                    check_sum=$checks
+                    mtime=$modified_epoch
                     itime=$ctime_epoch
                     mtime_sec=${mtime%%.*}
                     itime_sec=${itime%%.*}
-					mtime_frac=${mtime#*.}
-					mt=$(date -d "@$mtime_sec" +"$fmt")
+                    mtime_frac=${mtime#*.}
+                    mt=$(date -d "@$mtime_sec" +"$fmt")
                     ct=$(date -d "@$itime_sec" +"$fmt" 2> /dev/null)
-					fs=$a_sze
-					# the inode changed update all remaining stats
-					if (( ino != a_ino )); then
-						check_sum="None"
-						log_lineout $debug_log $debug_file "$log_date" "calculate_csum inode changed $a_ino vs $ino discarding checksum for: $file_path"
-						#i=$a_ino
-						#sym=$a_sym
-						#n=$a_nlnk
-						#onr=$a_onr
-						#grp=$a_grp
-						#pmr=$a_prm
-					fi
-					return 0
-				fi
+                    fs=$a_sze
+                    # the inode changed update all remaining stats
+                    if (( ino != a_ino )); then
+                        check_sum="None"
+                        log_lineout $debug_log $debug_file "$log_date" "calculate_csum inode changed $a_ino vs $ino discarding checksum for: $file_path"
+                        #i=$a_ino
+                        #sym=$a_sym
+                        #n=$a_nlnk
+                        #onr=$a_onr
+                        #grp=$a_grp
+                        #pmr=$a_prm
+                    fi
+                    return 0
+                fi
 
-			fi
-			if (( x > 0 )); then
-				read -r f1 f2 _ f3 f4 _ a_ino a_sym a_nlnk a_sze a_onr a_grp a_prm < <( stat --format="%y %z %i %A %h %s %U %G %a" "$file_path" 2>/dev/null)  # %A
-				[[ -z "$a_prm" ]] && break
-				mod_time="$f1 $f2"
-				c=$( date -d "$mod_time" +%s.%N 2>/dev/null)  # %6N
-				[[ -z "$c" ]] && log_lineout $debug_log $debug_file "$log_date" "calculate checksum failed to convert timestamp retry $(( max_retries - x ))" && return 1  # mtime required
+            fi
+            if (( x > 0 )); then
+                read -r f1 f2 _ f3 f4 _ a_ino a_sym a_nlnk a_sze a_onr a_grp a_prm < <( stat --format="%y %z %i %A %h %s %U %G %a" "$file_path" 2>/dev/null)  # %A
+                [[ -z "$a_prm" ]] && break
+                mod_time="$f1 $f2"
+                c=$( date -d "$mod_time" +%s.%N 2>/dev/null)  # %6N
+                [[ -z "$c" ]] && log_lineout $debug_log $debug_file "$log_date" "calculate checksum failed to convert timestamp retry $(( max_retries - x ))" && return 1  # mtime required
                 c=$(normalize_ts "$c")
 
-				# if it matches the find command or if two stats match return the checksum
-				if [[ "$c" == "$modified_epoch" && -n "$a_ino" && -n "$a_sze" ]] && (( ino == a_ino )) && (( sze == a_sze )); then
-					check_sum=$checks
-					if [[ -z "$prev_hash" ]]; then
-						return 0
-					else
-						mtime=$modified_epoch
-		                itime=$ctime_epoch
-			            mtime_sec=${mtime%%.*}
-			            itime_sec=${itime%%.*}
-						mtime_frac=${mtime#*.}
-						mt=$(date -d "@$mtime_sec" +"$fmt")
-		                ct=$(date -d "@$itime_sec" +"$fmt" 2> /dev/null)
-						return 0
-					fi
-				fi
+                # if it matches the find command or if two stats match return the checksum
+                if [[ "$c" == "$modified_epoch" && -n "$a_ino" && -n "$a_sze" ]] && (( ino == a_ino )) && (( sze == a_sze )); then
+                    check_sum=$checks
+                    if [[ -z "$prev_hash" ]]; then
+                        return 0
+                    else
+                        mtime=$modified_epoch
+                        itime=$ctime_epoch
+                        mtime_sec=${mtime%%.*}
+                        itime_sec=${itime%%.*}
+                        mtime_frac=${mtime#*.}
+                        mt=$(date -d "@$mtime_sec" +"$fmt")
+                        ct=$(date -d "@$itime_sec" +"$fmt" 2> /dev/null)
+                        return 0
+                    fi
+                fi
 
-	    		# else retry
-				modified_epoch=$c
-				change_time="$f3 $f4"
+                # else retry
+                modified_epoch=$c
+                change_time="$f3 $f4"
                 r=$( date -d "$change_time" +%s.%N 2>/dev/null)
-				[[ -n "$r" ]] && r=$(normalize_ts "$r") || log_lineout $debug_log $debug_file "$log_date" "calculate_csum Warning ct is null on retried. retry $(( max_retries - x ))" && return 1
-				ctime_epoch=$r
-				prev_hash="$checks"
+                [[ -n "$r" ]] && r=$(normalize_ts "$r") || { log_lineout $debug_log $debug_file "$log_date" "calculate_csum Warning ct is null on retried. retry $(( max_retries - x ))" ; return 1 ; }
+                ctime_epoch=$r
+                prev_hash="$checks"
                 sleep $delay
-			fi
-		else
-			break
-		fi
-	    (( x-- ))
-	done
+            fi
+        else
+            break
+        fi
+        (( x-- ))
+    done
 fi
 log_lineout $debug_log $debug_file "$log_date" "calculate_csum failed no checksum skipping. retry $(( max_retries - x ))"
 return 1
@@ -301,8 +307,8 @@ local log_date
 local cache_flg="false"
 local cdir="/tmp/dbctimecache/"
 
-r=""				;	sl=""
-lmt=""			;	nlinks=""
+r=""                ;    sl=""
+lmt=""            ;    nlinks=""
 cam="None"
 check_sum=""
 
@@ -322,24 +328,24 @@ mt=$(date -d "@$mtime_sec" +"$fmt")
 ct=$(date -d "@$itime_sec" +"$fmt")
 if [ -e "$cFILE" ] && [ -f "$cFILE" ]; then
     if [ -n "$mt" ]; then
-		[[ -z "$ct" ]] && log_lineout $7 $8 "$log_date" "Warning ct is null on input to pblk $1" && return 1
-		mtime=$( normalize_ts "$mtime")
-		itime=$(normalize_ts "$itime")
-		mtime_frac=${mtime#*.}
+        [[ -z "$ct" ]] && log_lineout $7 $8 "$log_date" "Warning ct is null on input to pblk $1" && return 1
+        mtime=$( normalize_ts "$mtime")
+        itime=$(normalize_ts "$itime")
+        mtime_frac=${mtime#*.}
 
-	    if [ "$4" == "true" ]; then
-			[[ "$sym" == l* ]] && sl="y" && check_sum="None"
-			if [[ -z "$sl" ]]; then
-				[[ -e "$CACHE_F" ]] && mtime_us=$(( $mtime_sec * 1000000 + (10#$mtime_frac) )) && r=$(get_cached $i $fs $mtime_us)
-		        if [[ -n "$r" ]]; then
-		            check_sum="$r"
-		        else
-					calculate_csum "main" "$cFILE" $mtime $i $fs 2 0 $debug_log $debug_file $log_date
-					csum_rlt=$?
-					(( csum_rlt == 0 )) || return 1
-		            cache_flg="true"
-		        fi
-			fi
+        if [ "$4" == "true" ]; then
+            [[ "$sym" == l* ]] && sl="y" && check_sum="None"
+            if [[ -z "$sl" ]]; then
+                [[ -e "$CACHE_F" ]] && mtime_us=$(( $mtime_sec * 1000000 + (10#$mtime_frac) )) && r=$(get_cached $i $fs $mtime_us)
+                if [[ -n "$r" ]]; then
+                    check_sum="$r"
+                else
+                    calculate_csum "main" "$cFILE" $mtime $i $fs 2 0 $debug_log $debug_file $log_date
+                    csum_rlt=$?
+                    (( csum_rlt == 0 )) || return 1
+                    cache_flg="true"
+                fi
+            fi
             if [[ -n "$check_sum" ]]; then
 
                 fs=${fs:-None} ; sl=${sl:-None}
@@ -348,7 +354,7 @@ if [ -e "$cFILE" ] && [ -f "$cFILE" ]; then
                 nlinks=$n
                 ats=$(date -d "@${atime%%.*}" +"$fmt")
 
-				ct=${ct:-None None}
+                ct=${ct:-None None}
                 ats=${ats:-None None}
                 lmt=${lmt:-None None}
 
@@ -359,9 +365,9 @@ if [ -e "$cFILE" ] && [ -f "$cFILE" ]; then
                     # change_t=$(echo "scale=0; $itime * 100000000 / 1" | bc)
                     # itime_frac=$(( change_t % 100000000 ))
                     itime_frac=${itime#*.}
-					itime_oct=$(( 10#$itime_frac ))
-					mtime_oct=$(( 10#$mtime_frac ))
-					mtime_us=$(( mtime_sec * 1000000 + mtime_oct))
+                    itime_oct=$(( 10#$itime_frac ))
+                    mtime_oct=$(( 10#$mtime_frac ))
+                    mtime_us=$(( mtime_sec * 1000000 + mtime_oct))
 
                     if (( itime_sec == mtime_sec && itime_oct > mtime_oct )) || (( itime_sec > mtime_sec )); then   # awk -v it="$itime" -v mt="$mtime" 'BEGIN {exit !(it > mt)}'; then
 
@@ -371,9 +377,13 @@ if [ -e "$cFILE" ] && [ -f "$cFILE" ]; then
 
                         output="$mt \"$y\" $ct $i $ats $adtcmd $cam $lmt $nlinks $mtime_us"
 
+                        flock -x 200
+
                         if [[ "$cache_flg" = "true" ]] && (( fs > 1000000 )); then [[ -d $cdir ]] || mkdir -p $cdir ; z="$( escf "$cFILE")" ; upt_cache "$i" "$fs" "$mtime_us" "$check_sum" "$z" "$6" ; fi
 
                         printf '%s\n' "$output" >> $2
+
+                        flock -u 200
 
                     else
                         log_lineout $7 $8 "$log_date" "pblk failed to process. itime $itime and mtime $mtime ctime was <= mtime skipped. line $1"
@@ -390,7 +400,7 @@ if [ -e "$cFILE" ] && [ -f "$cFILE" ]; then
             fi
         else
             log_lineout $7 $8 "$log_date" "pblk checksum is false skipping $1"
-	    fi
+        fi
     else
         log_lineout $7 $8 "$log_date" "Warning mt is null on input to pblk skipped $1"
     fi
